INSERT INTO "Vocabularies" ("Id", "Word", "Ipa", "AudioUrl", "CefrLevel", "PartOfSpeech", "ExampleSentence", "ContentSource", "CreatedAt") VALUES 
(gen_random_uuid(), 'apple', '/ˈæpəl/', null, 0, 'noun', 'I ate an apple.', 0, NOW()),
(gen_random_uuid(), 'book', '/bʊk/', null, 0, 'noun', 'I read a book.', 0, NOW()),
(gen_random_uuid(), 'cat', '/kæt/', null, 0, 'noun', 'The cat is sleeping.', 0, NOW()),
(gen_random_uuid(), 'dog', '/dɔɡ/', null, 0, 'noun', 'My dog is friendly.', 0, NOW()),
(gen_random_uuid(), 'egg', '/ɛɡ/', null, 0, 'noun', 'I had an egg for breakfast.', 0, NOW()),
(gen_random_uuid(), 'fish', '/fɪʃ/', null, 0, 'noun', 'The fish swims in the water.', 0, NOW()),
(gen_random_uuid(), 'good', '/ɡʊd/', null, 0, 'adj', 'This is a good book.', 0, NOW()),
(gen_random_uuid(), 'house', '/haʊs/', null, 0, 'noun', 'We live in a big house.', 0, NOW()),
(gen_random_uuid(), 'ice', '/aɪs/', null, 0, 'noun', 'I need some ice for my drink.', 0, NOW()),
(gen_random_uuid(), 'jump', '/dʒʌmp/', null, 0, 'verb', 'The children jump on the bed.', 0, NOW()),
(gen_random_uuid(), 'kite', '/kaɪt/', null, 0, 'noun', 'He flies a kite in the park.', 0, NOW()),
(gen_random_uuid(), 'love', '/lʌv/', null, 0, 'verb', 'I love my family.', 0, NOW()),
(gen_random_uuid(), 'mother', '/ˈmʌðər/', null, 0, 'noun', 'My mother is very kind.', 0, NOW()),
(gen_random_uuid(), 'name', '/neɪm/', null, 0, 'noun', 'What is your name?', 0, NOW()),
(gen_random_uuid(), 'open', '/ˈoʊpən/', null, 0, 'verb', 'Please open the door.', 0, NOW()),
(gen_random_uuid(), 'play', '/pleɪ/', null, 0, 'verb', 'They play football after school.', 0, NOW()),
(gen_random_uuid(), 'quiet', '/ˈkwaɪət/', null, 0, 'adj', 'The library is very quiet.', 0, NOW()),
(gen_random_uuid(), 'red', '/rɛd/', null, 0, 'adj', 'My favorite color is red.', 0, NOW()),
(gen_random_uuid(), 'sun', '/sʌn/', null, 0, 'noun', 'The sun is shining today.', 0, NOW()),
(gen_random_uuid(), 'tree', '/tri/', null, 0, 'noun', 'There is a big tree in the yard.', 0, NOW()),
(gen_random_uuid(), 'achieve', '/əˈtʃiv/', null, 1, 'verb', 'She hopes to achieve her goals.', 0, NOW()),
(gen_random_uuid(), 'believe', '/bɪˈliv/', null, 1, 'verb', 'I believe you are right.', 0, NOW()),
(gen_random_uuid(), 'careful', '/ˈkɛrfəl/', null, 1, 'adj', 'Be careful when you cross the street.', 0, NOW()),
(gen_random_uuid(), 'decide', '/dɪˈsaɪd/', null, 1, 'verb', 'He will decide what to do later.', 0, NOW()),
(gen_random_uuid(), 'enjoy', '/ɛnˈdʒɔɪ/', null, 1, 'verb', 'I really enjoy reading.', 0, NOW()),
(gen_random_uuid(), 'forget', '/fərˈɡɛt/', null, 1, 'verb', 'Dont forget to call me.', 0, NOW()),
(gen_random_uuid(), 'guess', '/ɡɛs/', null, 1, 'verb', 'Can you guess what it is?', 0, NOW()),
(gen_random_uuid(), 'happen', '/ˈhæpən/', null, 1, 'verb', 'What will happen next?', 0, NOW()),
(gen_random_uuid(), 'invite', '/ɪnˈvaɪt/', null, 1, 'verb', 'I will invite her to the party.', 0, NOW()),
(gen_random_uuid(), 'join', '/dʒɔɪn/', null, 1, 'verb', 'Do you want to join us?', 0, NOW()),
(gen_random_uuid(), 'keep', '/kip/', null, 1, 'verb', 'Keep the door closed.', 0, NOW()),
(gen_random_uuid(), 'learn', '/lɜrn/', null, 1, 'verb', 'I want to learn French.', 0, NOW()),
(gen_random_uuid(), 'matter', '/ˈmætər/', null, 1, 'noun', 'What is the matter?', 0, NOW()),
(gen_random_uuid(), 'notice', '/ˈnoʊtɪs/', null, 1, 'verb', 'Did you notice the sign?', 0, NOW()),
(gen_random_uuid(), 'offer', '/ˈɔfər/', null, 1, 'verb', 'They offer free delivery.', 0, NOW()),
(gen_random_uuid(), 'prepare', '/prɪˈpɛr/', null, 1, 'verb', 'She will prepare dinner.', 0, NOW()),
(gen_random_uuid(), 'quickly', '/ˈkwɪkli/', null, 1, 'adv', 'He ran quickly.', 0, NOW()),
(gen_random_uuid(), 'remember', '/rɪˈmɛmbər/', null, 1, 'verb', 'I remember you.', 0, NOW()),
(gen_random_uuid(), 'suggest', '/səɡˈdʒɛst/', null, 1, 'verb', 'I suggest we leave early.', 0, NOW()),
(gen_random_uuid(), 'travel', '/ˈtrævəl/', null, 1, 'verb', 'They love to travel.', 0, NOW()),
(gen_random_uuid(), 'abandon', '/əˈtʃiv/', null, 2, 'verb', 'They had to abandon the car.', 0, NOW()),
(gen_random_uuid(), 'balance', '/bɪˈliv/', null, 2, 'noun', 'Keep your balance.', 0, NOW()),
(gen_random_uuid(), 'calculate', '/ˈkɛrfəl/', null, 2, 'verb', 'Calculate the total cost.', 0, NOW()),
(gen_random_uuid(), 'damage', '/dɪˈsaɪd/', null, 2, 'noun', 'The storm caused damage.', 0, NOW()),
(gen_random_uuid(), 'educate', '/ɛnˈdʒɔɪ/', null, 2, 'verb', 'We must educate children.', 0, NOW()),
(gen_random_uuid(), 'familiar', '/fərˈɡɛt/', null, 2, 'adj', 'That face looks familiar.', 0, NOW()),
(gen_random_uuid(), 'gather', '/ɡɛs/', null, 2, 'verb', 'Let us gather around.', 0, NOW()),
(gen_random_uuid(), 'habit', '/ˈhæpən/', null, 2, 'noun', 'Smoking is a bad habit.', 0, NOW()),
(gen_random_uuid(), 'identify', '/ɪnˈvaɪt/', null, 2, 'verb', 'Can you identify the man?', 0, NOW()),
(gen_random_uuid(), 'jealous', '/dʒɔɪn/', null, 2, 'adj', 'She was jealous of him.', 0, NOW()),
(gen_random_uuid(), 'keen', '/kip/', null, 2, 'adj', 'He is keen on sports.', 0, NOW()),
(gen_random_uuid(), 'label', '/lɜrn/', null, 2, 'noun', 'Read the label carefully.', 0, NOW()),
(gen_random_uuid(), 'manage', '/ˈmætər/', null, 2, 'verb', 'I can manage it myself.', 0, NOW()),
(gen_random_uuid(), 'narrow', '/ˈnoʊtɪs/', null, 2, 'adj', 'The road is very narrow.', 0, NOW()),
(gen_random_uuid(), 'obey', '/ˈɔfər/', null, 2, 'verb', 'You must obey the rules.', 0, NOW()),
(gen_random_uuid(), 'package', '/prɪˈpɛr/', null, 2, 'noun', 'A package arrived for you.', 0, NOW()),
(gen_random_uuid(), 'qualify', '/ˈkwɪkli/', null, 2, 'verb', 'She needs to qualify.', 0, NOW()),
(gen_random_uuid(), 'rapid', '/rɪˈmɛmbər/', null, 2, 'adj', 'The river has rapid flow.', 0, NOW()),
(gen_random_uuid(), 'satisfy', '/səɡˈdʒɛst/', null, 2, 'verb', 'This will satisfy your hunger.', 0, NOW()),
(gen_random_uuid(), 'tackle', '/ˈtrævəl/', null, 2, 'verb', 'He tried to tackle the problem.', 0, NOW()),
(gen_random_uuid(), 'abolish', '/əˈtʃiv/', null, 3, 'verb', 'They want to abolish the law.', 0, NOW()),
(gen_random_uuid(), 'barrier', '/bɪˈliv/', null, 3, 'noun', 'Language can be a barrier.', 0, NOW()),
(gen_random_uuid(), 'campaign', '/ˈkɛrfəl/', null, 3, 'noun', 'They launched a campaign.', 0, NOW()),
(gen_random_uuid(), 'debate', '/dɪˈsaɪd/', null, 3, 'noun', 'The debate was interesting.', 0, NOW()),
(gen_random_uuid(), 'elaborate', '/ɛnˈdʒɔɪ/', null, 3, 'adj', 'An elaborate plan was made.', 0, NOW()),
(gen_random_uuid(), 'facility', '/fərˈɡɛt/', null, 3, 'noun', 'The facility is huge.', 0, NOW()),
(gen_random_uuid(), 'generate', '/ɡɛs/', null, 3, 'verb', 'Wind turbines generate power.', 0, NOW()),
(gen_random_uuid(), 'highlight', '/ˈhæpən/', null, 3, 'verb', 'Please highlight the main points.', 0, NOW()),
(gen_random_uuid(), 'illustrate', '/ɪnˈvaɪt/', null, 3, 'verb', 'Let me illustrate this.', 0, NOW()),
(gen_random_uuid(), 'justify', '/dʒɔɪn/', null, 3, 'verb', 'How do you justify that?', 0, NOW()),
(gen_random_uuid(), 'landscape', '/kip/', null, 3, 'noun', 'The landscape is beautiful.', 0, NOW()),
(gen_random_uuid(), 'maintain', '/lɜrn/', null, 3, 'verb', 'We must maintain the standard.', 0, NOW()),
(gen_random_uuid(), 'negotiate', '/ˈmætər/', null, 3, 'verb', 'They had to negotiate.', 0, NOW()),
(gen_random_uuid(), 'objective', '/ˈnoʊtɪs/', null, 3, 'noun', 'Our main objective is this.', 0, NOW()),
(gen_random_uuid(), 'participate', '/ˈɔfər/', null, 3, 'verb', 'Will you participate?', 0, NOW()),
(gen_random_uuid(), 'radical', '/prɪˈpɛr/', null, 3, 'adj', 'It was a radical change.', 0, NOW()),
(gen_random_uuid(), 'subsequent', '/ˈkwɪkli/', null, 3, 'adj', 'In subsequent years, things improved.', 0, NOW()),
(gen_random_uuid(), 'temporary', '/rɪˈmɛmbər/', null, 3, 'adj', 'This is a temporary solution.', 0, NOW()),
(gen_random_uuid(), 'ultimate', '/səɡˈdʒɛst/', null, 3, 'adj', 'The ultimate goal is peace.', 0, NOW()),
(gen_random_uuid(), 'variable', '/ˈtrævəl/', null, 3, 'noun', 'Weather is a variable.', 0, NOW()),
(gen_random_uuid(), 'abstract', '/əˈtʃiv/', null, 4, 'adj', 'It is an abstract concept.', 0, NOW()),
(gen_random_uuid(), 'bureaucracy', '/bɪˈliv/', null, 4, 'noun', 'The bureaucracy is slow.', 0, NOW()),
(gen_random_uuid(), 'cohere', '/ˈkɛrfəl/', null, 4, 'verb', 'The parts cohere well.', 0, NOW()),
(gen_random_uuid(), 'deduce', '/dɪˈsaɪd/', null, 4, 'verb', 'We can deduce the answer.', 0, NOW()),
(gen_random_uuid(), 'empirical', '/ɛnˈdʒɔɪ/', null, 4, 'adj', 'There is empirical evidence.', 0, NOW()),
(gen_random_uuid(), 'fluctuate', '/fərˈɡɛt/', null, 4, 'verb', 'Prices fluctuate daily.', 0, NOW()),
(gen_random_uuid(), 'hierarchy', '/ɡɛs/', null, 4, 'noun', 'The corporate hierarchy is strict.', 0, NOW()),
(gen_random_uuid(), 'imply', '/ˈhæpən/', null, 4, 'verb', 'What do you imply?', 0, NOW()),
(gen_random_uuid(), 'jurisdiction', '/ɪnˈvaɪt/', null, 4, 'noun', 'It falls under their jurisdiction.', 0, NOW()),
(gen_random_uuid(), 'kinship', '/dʒɔɪn/', null, 4, 'noun', 'A strong sense of kinship.', 0, NOW()),
(gen_random_uuid(), 'legislate', '/kip/', null, 4, 'verb', 'They plan to legislate against it.', 0, NOW()),
(gen_random_uuid(), 'margin', '/lɜrn/', null, 4, 'noun', 'A narrow margin of error.', 0, NOW()),
(gen_random_uuid(), 'notion', '/ˈmætər/', null, 4, 'noun', 'A strange notion.', 0, NOW()),
(gen_random_uuid(), 'obscure', '/ˈnoʊtɪs/', null, 4, 'adj', 'An obscure reference.', 0, NOW()),
(gen_random_uuid(), 'paradigm', '/ˈɔfər/', null, 4, 'noun', 'A new paradigm.', 0, NOW()),
(gen_random_uuid(), 'qualitative', '/prɪˈpɛr/', null, 4, 'adj', 'A qualitative analysis.', 0, NOW()),
(gen_random_uuid(), 'revenue', '/ˈkwɪkli/', null, 4, 'noun', 'The companys revenue.', 0, NOW()),
(gen_random_uuid(), 'simulate', '/rɪˈmɛmbər/', null, 4, 'verb', 'To simulate the conditions.', 0, NOW()),
(gen_random_uuid(), 'tangible', '/səɡˈdʒɛst/', null, 4, 'adj', 'Tangible benefits.', 0, NOW()),
(gen_random_uuid(), 'utilize', '/ˈtrævəl/', null, 4, 'verb', 'We must utilize our resources.', 0, NOW());

INSERT INTO "VocabularyTranslations" ("Id", "VocabularyId", "LanguageCode", "Meaning", "Explanation", "ExampleTranslation")
SELECT gen_random_uuid(), "Id", 'vi', 'Nghĩa của ' || "Word", 'Giải thích cho ' || "Word", 'Ví dụ tiếng Việt cho ' || "Word"
FROM "Vocabularies";
